[package]
name = "crib"
version = "0.0.0"
description = """Library and CLI for reading and writing genome track files."""
readme = "README.md"
authors = ["Garth Ilsley"]
license = "MIT OR Apache-2.0"
rust-version = "1.83"
edition = "2021"
repository = "https://github.com/gannot/crib"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
anyhow = "1.0.94"
thiserror = "2.0.9"
gannot = "0.0.2"
bigtools = "0.5.4"
url = "2.5.4"

